# Generated by Django 5.0 on 2024-10-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_type',
            field=models.CharField(choices=[('leader', 'cohort leader'), ('deputy', 'vice leader'), ('secretary', 'secretary'), ('president', 'president'), ('member', 'member')], default='member', max_length=100),
        ),
    ]
